dist: xenial
sudo: require
language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - qemu-system-x86
      - nasm
      - g++
      - python3-matplotlib
      - python3-tk

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/tup
  - sudo apt-get update -q
  - sudo apt-get install -y tup

script:
    - tup
    - cat measurements.csv
