dist: bionic
language: cpp
compiler: gcc
addons:
  apt:
    update: true

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/tup
  - sudo add-apt-repository -y ppa:jacob/virtualisation
  - sudo apt-get update -q
  - sudo apt-get install -y tup qemu-system-x86 nasm g++ python3-matplotlib

script:
    - tup
    - cat measurements.csv
